### ISSUE TITLE
Callbacks for appDidFinishLaunching and registeredForRemoteNotifications missing

### ISSUE THREAD

**Issue by gautamMoEngage** [segment-integrations/analytics-ios-integration-moengage#1]
Hi @f2prateek , 

There are a couple of callbacks missing, registering for push being the critical one. Can you give permissions for the repo so I can push the code, or would I still have to create a pull request?

**Comment by f2prateek** [comment]
You'll still have to make a pull request. Once we move it to MoEngage's org, you won't have to do that.

**Comment by f2prateek** [comment]
@gautamMoEngage for migrating the integration to MoEngage - i've listed the steps here:
1. Partner: Fork the integration repo to your own org
2. Partner: Rename spec to your namespace that you can publish to
3. Partner: Reset version to 1.0.0
4. Partner: Release 1.0.0
5. Segment: Update pointers in metadata
6. Segment: Deprecate original repo and spec

**Comment by f2prateek** [comment]
Ping me once you've done step 4 and we can finish the migration!
